### ISSUE TITLE
Going for complete dot access

### ISSUE THREAD

**Issue by kootenpv** [phonkee/vcontext#1]
Why 

```
context['result.0.user.username'] = 'phonkee'
```

and not 

```
context.result.0.user.username = 'phonkee'
```

?

**Comment by phonkee** [comment]
I have considered the idea of getattr, but it's impossible to use integer in dot notation.
Then it should be context.result[0]user.username
I rather used **getitem** approach since I want to pass directly strings to Context data structure.
Also it would be harder to create new items with getattr approach, since then you should maintain a state.
Example:
context.attr[0]
If attribute `attr` does not exist, you don't know what datastructure to create directory or list.
